name: mlops-ci-demo
on: [push] # You can trigger the pipeline in any branch, or a specific branch you define
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Define the steps of the pipeline here
          pip install -r requirements.txt
          python model.py
